services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./nginx/www/:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./nginx/log/:/var/log/nginx/
    depends_on:
      - node-app
    networks:
      - app-network

  node-app:
    container_name: node-app
    build:
      context: .
      dockerfile: node-app/Dockerfile
    volumes:
      - ./node-app:/usr/src/app
    networks:
      - app-network



networks:
  app-network:
    driver: bridge
  
